# Autogenerated wrapper script for MFEM_seq_jll for i686-w64-mingw32-cxx03
export libmfem

JLLWrappers.@generate_wrapper_header("MFEM_seq")
JLLWrappers.@declare_library_product(libmfem, "libmfem.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmfem,
        "bin\\libmfem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
